This revision adds the implementation of homework 3, part 1 of the SaaS class from Berkeley. However, it only includes the implementation for the "sort movie list" feature. Since this revision uses a newer version of Capybara, the suggestion to use "page.content" in the movie_steps failed as follows:
undefined method `content' for #<Capybara::Session> (NoMethodError)
./features/step_definitions/movie_steps.rb:20:in `/I should see "(.*)" before "(.*)"/'
features/sort_movie_list.feature:29:in `Then I should see "Amelie" before "Chocolat"'

Some description about Capybara methods and versions is on http://stackoverflow.com/questions/8688925/capybara-rspec

* sort_movie_list.feature
- Implementing the scenario of sorting the movies alphabetically
- Implementing the scenario of sorting the movies by date

* movie_steps.rb
- Implementing the step methods to create the movies
- Using page.all as the "page.content" resulted in undefined method as decribed above.